### ISSUE TITLE
Improve message index styles

### ISSUE THREAD

**Issue by vit1251** [vit1251/golden#140]
- Switch on HTML fluxbox layout;

**Comment by ftoledo** [comment]
just an idea... support custom css style..you can add a textbox on the setup page to user can write css that override the default styles.

**Comment by vit1251** [comment]
> just an idea... support custom css style..you can add a textbox on the setup page to user can write css that override the default styles.

Look like advanced feature for hackers. I think that usual user does not do this.

**Comment by ftoledo** [comment]
> > just an idea... support custom css style..you can add a textbox on the setup page to user can write css that override the default styles.
> 
> Look like advanced feature for hackers. I think that usual user does not do this.

No need to be hacker to write some css styles.. 
example: a visual impired just can add this text:

```
.panel {
 background: white;
 }

.label {
 color: black;
font-size: 40px;
}
```
and pseudo code at the templates for <header/>:

if the settings('custom_css') is not empy {
   just print settings('custom_css')
}

=)

**Comment by vit1251** [comment]
Developers who want add custom css may improve Golden and provide themes with register in contribution list.
Users just use application as is (out of box). Your idea look like provide SQL query input on web sites for users.

**Comment by streaps** [comment]
I agree with @ftoledo, custom css would be a neat feature.

**Comment by vit1251** [comment]
I'm misunderstanding desire to source code UI styles customize in a runtime. It can be assumed that we are trying to solve the problem of adding styles soon, but there is astray.

I think that there is more of a desire to customize styles require a more basic mechanism, and that mechanism is themes.

I welcome developer/designer/user source code contributing to improve themes and as you can see we welcome logo improving and more styles in next version.

**Comment by vit1251** [comment]
Some users insist on improvements and present tasks to me as debt, which provides me with routine and boring development tasks.

For example, adding styles, customizing keyboard habits, or localizing an application.

If I do not share these values, then I will not make such a contribution to the development and this is already a matter of management and policy.

At the same time, people want to make their contribution without spending their efforts. I find this position of people unpleasant. If you have a desire to contribute, then this is voluntary and accepted as a donation, not as a debt.

**Comment by vit1251** [comment]
I propose to discuss the further development of the topic of styles in a special GitHUB discussion section, since the work on this task: switch on flux HTML layout is almost completed (small alignments issue here) and I do not have plan to continue work here.
