### ISSUE TITLE
Some idea when possible make Golden possible to send a notification into the browser as popup

### ISSUE THREAD

**Issue by ruditimmermans** [vit1251/golden#147]
Vitold,

I dont know if it would be possible but when there would be new echomail or  netmail that Golden send some popup nothification into the browser when you are into a other tab you will see this ?

Thanks!

**Comment by vit1251** [comment]
Let I try to make counter update over periodic server pulling. Please check new feature in master.

**Comment by ruditimmermans** [comment]
I have test it and it works great !! thanks!
