### ISSUE TITLE
Add screenshots to the general description of the application

### ISSUE THREAD

**Issue by Korb** [vit1251/golden#156]
I suggest adding at least one screenshot of the main application window to README.md. And better, also a few settings tabs, hiding them in the spoiler.

**Comment by vit1251** [comment]
What goal will we achieve by placing a screenshot of the application in README.md? How do you feel about posting a screenshot in the Wiki section and not in the README.md file? Does it make sense in your opinion to store the image in the repository?

**Comment by Korb** [comment]
@vit1251, it seems to me that if a user who is not familiar with this project ends up on its main page, it will be convenient for him to see a brief description of the application and its appearance. Without the need to collect this basic information from different sources. Do you disagree?

**Comment by vit1251** [comment]
I think that one well compressed image does't  create many source code clone delay. Can you create MR with screenshot?

On the other hand, for those unfamiliar with the application, there is a separate channel on YouTube and I welcome video blogger with own video to place on that channel (corresponding to YouTube standards). More details at the link
https://www.youtube.com/channel/UC6Ll7yKcrOiCkTCZyIcCUTA

**Comment by vit1251** [comment]
OK. I will create some screenshot and add this as documentation directory.
Please check.
