### ISSUE TITLE
Using local timezone for message without TZUTC

### ISSUE THREAD

**Issue by vit1251** [vit1251/golden#97]

**Comment by streaps** [comment]
why not use UTC time? local timezone is also wrong with international mail.

**Comment by vit1251** [comment]
I don't know. I actually try reimplement Fido software by standard. Do u know standart about using UTC time in this case?

**Comment by streaps** [comment]
The thing is that there is not one (universal) local time in the world, but multiple time zones with 38 UTC offsets. Without a TZUTC kludge there is no way (for the software) to know the time zone the message was written and there is no standard that defines that you should apply the local time zone (on the receiving end). It's undefined. 

Using UTC for mails without the TZUTC kludge is just my personal preference. What do you think of a configuration option for setting the default timezone? And maybe some prefer to see the plain time as it is in the mail without any modification.

Should I open an issue for a feature request?

**Comment by vit1251** [comment]
@streaps quick responses below.

> What do you think of a configuration option for setting the default timezone?

I think that user already have their timezone on comuter and this zone is known as Local timezone.
But you right that software does not know BOSS timezone and user CAN set this parameter in application settings.
By design in 80's network work over one timezone only and this problem come with wide network connections. 

> And maybe some prefer to see the plain time as it is in the mail without any modification.

This application for point who want join to FidoNet as reader and writer message. I does not want to assume use case to determine node settings error or investigate node problem. There just simple application like well known forum or social network. I does not seen before that some social network site provide internal protocol for user for investigate internal
problem.

> Should I open an issue for a feature request?

Yes, sure. It is open source code you can propogate ideas, create issues, prupose pull requests and etc.
